name: Snyk Golang Scan
on: pull_request
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Snyk Monitor
        uses: eeveebank/github-actions-snyk/monitor@master
        with:
          org_id: ${{ secrets.SNYK_PLATFORM_TOOLS_ORG_ID }}
          repository_name: ${{ github.event.repository.name }}
          snyk_token: ${{ secrets.SNYK_PLATFORM_TOOLS_TOKEN }}
          integration_id: ${{ secrets.SNYK_PLATFORM_TOOLS_INTEGRATION_ID }}
      - uses: actions/checkout@v2
      - name: Run Snyk Golang Scanning
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_PLATFORM_TOOLS_TOKEN }}
